version: '3.6'

services:

  influxdb:
    image: influxdb:1.6-alpine
    ports:
      - "8086:8086"
    volumes:
      - /data/configs/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influxdb:/var/lib/influxdb
    networks:
      - influxdb
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    networks:
      - elasticsearch
    environment:
      discovery.type: single-node
    volumes:
      - elasticsearch-conf:/usr/share/elasticsearch/config
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-logs:/usr/share/elasticsearch/logs
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 104857600 # 100 Mb
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

networks:
  influxdb:
  elasticsearch:

volumes:
  influxdb:
  elasticsearch-conf:
  elasticsearch-data:
  elasticsearch-logs:
