version: '3.7'

services:

  influxdb:
    image: influxdb:1.7-alpine
    volumes:
      - /data/influxdb:/var/lib/influxdb
    networks:
      - influxdb
    environment:
      INFLUXDB_REPORTING_DISABLED: 'true'
      INFLUXDB_BIND_ADDRESS: ':8088'
      INFLUXDB_DATA_INDEX_VERSION: 'tsi1'
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
      INFLUXDB_HTTP_LOG_ENABLED: 'false'
      INFLUXDB_HTTP_MAX_ROW_LIMIT: '10000'
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    networks:
      - elasticsearch
    environment:
      discovery.type: single-node
    volumes:
      - elasticsearch-conf:/usr/share/elasticsearch/config
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-logs:/usr/share/elasticsearch/logs
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 104857600 # 100 Mb
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

networks:
  influxdb:
  elasticsearch:

volumes:
  influxdb:
  elasticsearch-conf:
  elasticsearch-data:
  elasticsearch-logs:
