version: '3.6'

services:

  influxdb:
    image: influxdb:1.5-alpine
    ports:
      - "8086:8086"
    volumes:
      - /data/configs/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influxdb:/var/lib/influxdb
    networks:
      - influxdb
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

networks:
  influxdb:

volumes:
  influxdb:
