version: '3.7'

services:

  influxdb:
    image: influxdb:1.7-alpine
    volumes:
      - /data/influxdb:/var/lib/influxdb
    networks:
      - influxdb
    environment:
      INFLUXDB_REPORTING_DISABLED: 'true'
      INFLUXDB_BIND_ADDRESS: ':8088'
      INFLUXDB_DATA_INDEX_VERSION: 'tsi1'
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
      INFLUXDB_HTTP_LOG_ENABLED: 'false'
      INFLUXDB_HTTP_MAX_ROW_LIMIT: '10000'
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

networks:
  influxdb:
