version: '3.7'

services:

  d01:
    image: andyceo/phpdevenv:latest
    volumes:
      - /data/developers/developer-01:/root
    networks:
      - testnet_ergo
      - nginx
      - influxdb
      - influxdbsys
      - explorer
      - elasticsearch
    ports:
      - "40023:22"
      - "48889:8888"
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01
      mode: replicated
      replicas: 1
      restart_policy:
        # any to allow 'kill 1' works in container.
        # 'kill 1' will recreate container.
        condition: any

  d02:
    image: andyceo/phpdevenv:latest
    volumes:
      - /data/developers/developer-02:/root
    networks:
      - testnet_ergo
      - nginx
      - influxdb
      - influxdbsys
      - explorer
      - elasticsearch
    ports:
      - "40024:22"
      - "48890:8888"
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

networks:
  testnet_ergo:
    external: true
  nginx:
    external: true
    name: httpd_nginx
  influxdb:
    external: true
    name: databases_influxdb
  influxdbsys:
    external: true
    name: monitoring_influxdbsys
  explorer:
    external: true
    name: explorer_postgres
  elasticsearch:
    external: true
    name: databases_elasticsearch
