version: '3.6'

services:

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-at-postgres
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    networks:
      - postgres
    secrets:
      - postgres-at-postgres
    deploy:
      placement:
        constraints:
          - node.hostname == explorer

  back:
    image: ergoplatform/explorer-back
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/explorer
      DB_USER: ergo
      DB_PASS_FILE: /run/secrets/ergo-at-postgres
    networks:
      - postgres
      - nginx
    secrets:
      - ergo-at-postgres
    deploy:
      placement:
        constraints:
          - node.hostname == explorer

  front:
    image: ergoplatform/ergo-explorer
    volumes:
      - /data/configs/ergo-explorer/app.config.js:/usr/src/app/build/client/app.config.js:ro
    networks:
      - nginx
    deploy:
      placement:
        constraints:
          - node.hostname == explorer

networks:
  nginx:
    external: true
    name: httpd_nginx
  postgres:

volumes:
  postgres:

secrets:
  postgres-at-postgres:
    external: true
  ergo-at-postgres:
    external: true
