version: '3.6'

services:

  back:
    image: ergoplatform/explorer-back
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/explorer
      DB_USER: ergo
      DB_PASS_FILE: /run/secrets/ergo-at-postgres
    networks:
      - postgres
      - nginx
    secrets:
      - ergo-at-postgres

  front:
    image: ergoplatform/ergo-explorer
    environment:
      REACT_APP_API_URL: https://api.testnet.ergoplatform.com/
    networks:
      - nginx

networks:
  postgres:
    external: true
    name: databases_postgres
  nginx:
    external: true
    name: infrastructure_nginx

secrets:
  ergo-at-postgres:
    external: true
