version: '3.7'

services:

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-at-postgres-mainnet
    secrets:
      - postgres-at-postgres-mainnet
    volumes:
      - /data/postgres:/var/lib/postgresql/data:rw
    networks:
      - postgres
    deploy:
      placement:
        constraints:
          - node.hostname == explorer-mainnet

  back:
    image: ergoplatform/explorer-back
    environment:
      DB_URL: jdbc:postgresql://explorer-mainnet_postgres:5432/explorer
      DB_USER: ergo
      DB_PASS_FILE: /run/secrets/ergo-at-postgres-mainnet
#      KNOWN_PEERS: '[“http://139.59.29.87:9053”, “http://159.65.11.55:9053", "http://165.227.26.175:9053"]'
      # bangalore
      PEER_1: http://139.59.29.87:9053
      # singapore
      PEER_2: http://159.65.11.55:9053
      # sf
      PEER_3: http://165.227.26.175:9053
      IS_TESTNET: 'false'
      GENESIS_ADDR: 2Z4YBkDsDvQj8BX7xiySFewjitqp2ge9c99jfes2whbtKitZTxdBYqbrVZUvZvKv6aqn9by4kp3LE1c26LCyosFnVnm6b6U1JYvWpYmL2ZnixJbXLjWAWuBThV1D6dLpqZJYQHYDznJCk49g5TUiS4q8khpag2aNmHwREV7JSsypHdHLgJT7MGaw51aJfNubyzSKxZ4AJXFS27EfXwyCLzW1K6GVqwkJtCoPvrcLqmqwacAWJPkmh78nke9H4oT88XmSbRt2n9aWZjosiZCafZ4osUDxmZcc5QVEeTWn8drSraY3eFKe8Mu9MSCcVU
    networks:
      - postgres
      - nginx
    secrets:
      - ergo-at-postgres-mainnet
    deploy:
      placement:
        constraints:
          - node.hostname == explorer-mainnet

  front:
    image: ergoplatform/ergo-explorer
    volumes:
      - /data/configs/ergo-explorer-mainnet/app.config.js:/usr/src/app/build/client/app.config.js:ro
    networks:
      - nginx
    deploy:
      placement:
        constraints:
          - node.hostname == explorer-mainnet

networks:
  nginx:
    external: true
    name: httpd_nginx
  postgres:

secrets:
  ergo-at-postgres-mainnet:
    external: true
  postgres-at-postgres-mainnet:
    external: true
