version: '3.7'

services:

  portainer:
    image: portainer/portainer
    networks:
      - nginx
    volumes:
      - /data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

  adminer:
    image: adminer:4-standalone
    networks:
      - postgres
      - postgres-mainnet
      - nginx

  dockerhub-webhooks:
    image: andyceo/dockerhub-webhooks
    networks:
      - nginx
    volumes:
      - /data/configs/dockerhub-webhooks/config.json:/app/config.json
      - /data/stacks:/data/stacks
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

networks:
  nginx:
    external: true
    name: httpd_nginx
  influxdb:
    external: true
    name: databases_influxdb
  postgres:
    external: true
    name: explorer_postgres
  postgres-mainnet:
    external: true
    name: explorer-mainnet_postgres
