version: '3.6'

services:

  certificates:
    image: andyceo/monitoring-certificate
    command: --daemon
    environment:
      INFLUXDB_HOST: 'influxdb'
      INFLUXDB_PORT: 8086
      INFLUXDB_USER: telegraf
      INFLUXDB_PASSWORD_FILE: /run/secrets/telegraf-at-influxdb
      INFLUXDB_DATABASE: telegraf
    secrets:
      - telegraf-at-influxdb
    networks:
      - influxdb
    volumes:
      - certbot-etc:/etc/letsencrypt:ro
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

  telegraf:
    image: telegraf:alpine
    networks:
      - influxdb
      - nginx
      - explorer_postgres
    volumes:
      - /data/configs_rendered/inswarm.conf:/etc/telegraf/telegraf.conf:ro

  kapacitor:
    image: kapacitor:1.5-alpine
    volumes:
      - kapacitor-lib:/var/lib/kapacitor:rw
      - kapacitor-log:/var/log/kapacitor:rw
      - /data/configs/kapacitor:/etc/kapacitor:ro
    networks:
      - influxdb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm01

  node-info-monitor-209-97-138-187-mine1:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://209.97.138.187:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-209-97-134-210-mine2:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://209.97.134.210:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-209-97-136-204-light:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://209.97.136.204:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-78-46-93-239:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://78.46.93.239:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-88-198-13-202:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://88.198.13.202:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-ergo-dsalab-de:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://ergo.dsalab.de:9051"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-aleksey:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://188.166.109.25:48890"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-78-46-93-239-19052:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://78.46.93.239:19052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

networks:
  influxdb:
    external: true
    name: databases_influxdb
  nginx:
    external: true
    name: infrastructure_nginx
  explorer_postgres:
    external: true

secrets:
  telegraf-at-influxdb:
    external: true
  testnet-at-influxdb:
    external: true

volumes:
  certbot-etc:
    external: true
    name: infrastructure_certbot-etc
  kapacitor-lib:
  kapacitor-log:
