version: '3.7'

services:

  influxdbsys:
    image: influxdb:1.7-alpine
    ports:
      - mode: host
        target: 8086
        published: 8086
        protocol: tcp
      - mode: host
        target: 8089
        published: 8089
        protocol: udp
    networks:
      - influxdbsys
    volumes:
      - /data/influxdbsys:/var/lib/influxdb:rw
    environment:
      INFLUXDB_REPORTING_DISABLED: 'true'
      INFLUXDB_BIND_ADDRESS: ':8088'
      INFLUXDB_DATA_INDEX_VERSION: 'tsi1'
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
      INFLUXDB_HTTP_LOG_ENABLED: 'false'
      INFLUXDB_HTTP_MAX_ROW_LIMIT: '10000'
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

  grafana:
    image: grafana/grafana:5.4.3
    networks:
      - nginx
      - influxdb
      - influxdbsys
    # For configuration examples, @see http://docs.grafana.org/installation/docker/
    environment:
      GF_SERVER_ROOT_URL: "https://grafana.ergoplatform.com"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - /data/grafana:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

  certificates:
    image: andyceo/monitoring-certificate
    command: --daemon
    environment:
      INFLUXDB_HOST: 'influxdbsys'
      INFLUXDB_PORT: 8086
      INFLUXDB_USER: telegraf
      INFLUXDB_PASSWORD_FILE: /run/secrets/telegraf-at-influxdb
      INFLUXDB_DATABASE: telegraf
    secrets:
      - telegraf-at-influxdb
    networks:
      - influxdbsys
    volumes:
      - /data/certbot/etc:/etc/letsencrypt:ro
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

  telegraf:
    image: telegraf:alpine
    networks:
      - influxdbsys
      - nginx
      - explorer_postgres
    volumes:
      - /data/configs_rendered/inswarm.conf:/etc/telegraf/telegraf.conf:ro

  kapacitor:
    image: kapacitor:1.5-alpine
    volumes:
      - /data/kapacitor:/var/lib/kapacitor:rw
      - /data/logs/kapacitor:/var/log/kapacitor:rw
      - /data/configs_rendered/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - /data/configs/kapacitor/load:/etc/kapacitor/load:ro
    networks:
      - influxdb
      - influxdbsys
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm01


  node-info-monitor-209-97-138-187-mine1:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://209.97.138.187:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-209-97-134-210-mine2:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://209.97.134.210:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-209-97-136-204-light:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://209.97.136.204:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-testnet2-mine1-199:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://159.65.139.199:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-testnet2-mine1-185:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://206.189.130.185:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-testnet2-mine1-162:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://159.203.36.162:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-78-46-93-239:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://78.46.93.239:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-88-198-13-202:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://88.198.13.202:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-ergo-dsalab-de:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://ergo.dsalab.de:9051"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-aleksey:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://188.166.109.25:48890"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-78-46-93-239-19052:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://78.46.93.239:19052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-178-128-162-150:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://178.128.162.150:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

  node-info-monitor-93-123-180-164:
    image: ergoplatform/node-info-monitor
    environment:
      MONITORING_NODE_URL: "http://93.123.180.164:9052"
    secrets:
      - testnet-at-influxdb
    networks:
      - influxdb

networks:
  influxdb:
    external: true
    name: databases_influxdb
  influxdbsys:
  nginx:
    external: true
    name: httpd_nginx
  explorer_postgres:
    external: true

secrets:
  telegraf-at-influxdb:
    external: true
  testnet-at-influxdb:
    external: true
