---

- hosts: mainnet
  become: yes

  roles:
    - role: andyceo.preconf
      tags:
        - preconf
        - init

    - role: andyceo.configurator
      tags:
        - configurator

  tasks:
    - name: Start Ergo as daemon
      shell: daemon --chdir=/data/ergo -- java -Xmx3G -jar /data/ergo/ergo.jar --devnet -c /data/ergo/application.conf
      args:
        chdir: /data/ergo
      tags:
        - startnet
        - skip_ansible_lint

    - name: Stop Ergo daemon
      shell: pkill -f 'daemon -- java'
      tags:
        - stopnet
        - skip_ansible_lint

    - name: Remove Ergo data
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /.ergo
        - /data/ergo/.ergo
      tags:
        - removedata
        - skip_ansible_lint

    - name: Check Ergo node is running
      shell: pgrep -f 'daemon -- java'
      register: checknet
      changed_when: false
      tags:
        - checknet
        - skip_ansible_lint

    - name: Check Ergo node is running - print results
      debug:
        msg: "{{ checknet.stdout_lines }}"
      tags:
        - checknet
        - skip_ansible_lint

    - name: Send authorized key taken from file to ergo nodes
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', 'files/users/root-at-dergo1/id_rsa.pub') }}"
      tags:
        - sendssh
