version: '3.5'

services:

  influxdb:
    image: influxdb:1.4-alpine
    volumes:
      - /data/configs/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influxdb:/var/lib/influxdb
    networks:
      - influxdb
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

networks:
  influxdb:

volumes:
  influxdb:
