version: '3.4'

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx
    volumes:
      - /data/configs/nginx:/etc/nginx:ro
      - nginx-logs:/var/log/nginx
      - /data/configs/nginx/ssl:/ssl
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

  jenkins:
    image: jenkins/jenkins:lts-alpine
    networks:
      - nginx
    volumes:
      - jenkins:/var/jenkins_home
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/jenkins_home/sbt/bin
      JAVA_OPTS: -Dhudson.footerURL=https://jenkins.ergoplatform.com -Djava.awt.headless=true -Dhudson.security.csrf.requestfield=crumb -Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/Moscow -Xms128m -Xmx512m
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

  grafana:
    image: grafana/grafana:4.6.3
    networks:
      - nginx
    environment:
      GF_SERVER_ROOT_URL: "https://grafana.ergoplatform.com"
    volumes:
      - grafana-data:/var/lib/grafana:rw
      - grafana-logs:/var/log/grafana:rw
      - grafana-conf:/etc/grafana:rw
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

  portainer:
    image: portainer/portainer
    networks:
      - nginx
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

networks:
  nginx:

volumes:
  portainer:
  grafana-data:
  grafana-logs:
  grafana-conf:
  jenkins:
  nginx-logs:
