version: '3.4'

services:

  jenkins:
    image: jenkins/jenkins:lts-alpine
    ports:
      - "8080:8080"
    volumes:
      - jenkins:/var/jenkins_home
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/jenkins_home/sbt/bin
      JAVA_OPTS: -Dhudson.footerURL=https://jenkins.ergoplatform.com -Djava.awt.headless=true -Dhudson.security.csrf.requestfield=crumb -Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/Moscow -Xms128m -Xmx512m
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

  grafana:
    image: grafana/grafana:4.6.3
    environment:
      GF_SERVER_ROOT_URL: "https://grafana.ergoplatform.com"
    volumes:
      - grafana-data:/var/lib/grafana:rw
      - grafana-log:/var/log/grafana:rw
      - grafana-conf:/etc/grafana:rw
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

  portainer:
    image: portainer/portainer
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.hostname == swarm01

volumes:
  portainer:
  grafana-data:
  grafana-log:
  grafana-conf:
  jenkins:
